name: SwiftUI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test 1:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

    - name: Run tests
      run: |
        xcodebuild test \
        -scheme MySwiftUIApp \
        -project MySwiftUIApp.xcodeproj \
        -destination 'platform=iOS Simulator,name=iPhone 14'
