name: SwiftUI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        xcodebuild test \
        -scheme MySwiftUIApp \
        -project MySwiftUIApp.xcodeproj \
        -destination 'platform=iOS Simulator,name=iPhone 14'
